name: Bug Report
description: Report a bug to help us improve the project.
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for contributing to our project by reporting a bug! To help us understand and resolve the issue as quickly as possible, please provide the following details.

  - type: input
    id: title
    attributes:
      label: Basic Information - Title
      description: "A concise, descriptive summary of the issue. e.g., '[Bug]: MiniMax-M1 fails to initialize MCP tools'"
      placeholder: "[Bug]: Your concise issue title here"
    validations:
      required: true

  - type: dropdown
    id: models-used
    attributes:
      label: Basic Information - Models Used
      description: "Please select all applicable models. If \"Other,\" please specify in the scenario description."
      options:
        - MiniMax-M1
        - speech-02-hd
        - Other (Specify in Scenario)
    validations:
      required: true

  - type: textarea
    id: scenario-description
    attributes:
      label: Basic Information - Scenario Description
      description: "Briefly describe the context in which the bug occurred. e.g., \"Attempting to integrate Minimax-M1 as an MCP tool results in an error.\""
      placeholder: Describe the scenario here.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---
        ### Problem Validation
        To help us narrow down the cause, please confirm the following:

  - type: checkboxes
    id: problem-validation
    attributes:
      label: Confirmations
      options:
        - label: "I have thoroughly reviewed and followed the GitHub READMEs for `Minimax-MCP` and `Minimax-MCP-JS`."
          required: true
        - label: "I have checked the official Minimax documentation and found no relevant solution."
          required: true
        - label: "I have reviewed the relevant framework documentation (if applicable) and found no useful information."
          required: true
        - label: "I have searched existing GitHub issues and confirmed that this bug has not been reported previously."
          required: true

  - type: markdown
    attributes:
      value: |
        ---
        ### Environment Details
        Please provide comprehensive information about your development environment:

  - type: textarea
    id: system-information
    attributes:
      label: Environment Details - System Information
      description: "Include details such as your operating system, Python version, relevant software versions, and GPU information if applicable."
      placeholder: |
        OS: Ubuntu 22.04 LTS
        Python: 3.9.18
        CUDA: 11.8
        GPU: NVIDIA A100
    validations:
      required: true

  - type: textarea
    id: python-packages
    attributes:
      label: Environment Details - Python Packages (`pip list`)
      description: "Please paste the complete output of `pip list`."
      render: python
    validations:
      required: true

  - type: input
    id: trace-id
    attributes:
      label: Environment Details - Trace-ID
      description: "If applicable, please copy and paste the trace-ID of the problematic request."
      placeholder: "e.g., abcdef1234567890"

  - type: markdown
    attributes:
      value: |
        ---
        ### Description of the Bug
        Please provide a detailed description of the bug, following the recommended structure below. Feel free to modify it as needed.

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Description of the Bug - Steps to Reproduce
      description: "Provide clear, numbered steps to reproduce the issue."
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Description of the Bug - Expected Behavior
      description: "What did you expect to happen when performing the steps above?"
      placeholder: Describe what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Description of the Bug - Actual Behavior
      description: "What actually happened, detailing the unexpected outcome?"
      placeholder: Describe what actually happened.
    validations:
      required: true

  - type: textarea
    id: error-logs
    attributes:
      label: Description of the Bug - Error Logs (if any)
      description: "Please paste any relevant error messages or console output."
      render: bash
      placeholder: |
        Error message or log output here.
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Description of the Bug - Screenshots
      description: "Please paste any screenshots of the error or unexpected behavior here. You can drag and drop images directly into this field."
    validations:
      required: false
