name: Bug Report for MCP&API
description: Report a bug related to MCP and API tasks to help us reproduce and fix the problem.
title: "[Bug for MCP&API]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for contributing to our project by reporting a bug! To help us understand and resolve the issue as quickly as possible, please provide the following details.

  - type: dropdown
    id: models-used
    attributes:
      label: Basic Information - Models Used
      description: "Please select all applicable models."
      options:
        - MiniMax-M1
        - MiniMax-Text-01
        - speech-02-hd
        - speech-02-turbo
        - MiniMax Hailuo 02
        - T2V-01-Director
        - I2V-01-Director
        - S2V-01
        - music-1.5
        - music-01
        - image-01
    validations:
      required: true

  - type: input
    id: scenario-description
    attributes:
      label: Basic Information - Scenario Description
      description: | 
        Please briefly describe the scenario, including the framework or the platform, 
      placeholder: "ex: Minimax-M1 cannot be called as MCP tools. "
    validations:
      required: true

  - type: checkboxes
    id: problem-validation
    attributes:
      label: Confirmations
      options:
        - label: "I have followed the GitHub READMEs for [`Minimax-MCP`](https://github.com/MiniMax-AI/MiniMax-MCP) and [`Minimax-MCP-JS`](https://github.com/MiniMax-AI/MiniMax-MCP-JS)."
          required: true
        - label: "I have checked the [official Minimax documentation](https://www.minimax.io/platform_overview) and found no solution."
          required: true
        - label: "I have reviewed the relevant framework documentation (if applicable) and found no useful information."
          required: true
        - label: "I have searched [existing GitHub issues](https://github.com/MiniMax-AI/MiniMax-MCP/issues) and confirmed that this bug has not been reported previously."
          required: true

  - type: textarea
    attributes:
      label: Information about environment
      description: |
        Please provide information about you environment, 
        e.g., the software versions and the information on the OS, GPUs, if available.
      placeholder:
        "For example:
        - OS: Ubuntu 24.04
        - Python: Python 3.11
        - PyTorch: 2.6.0+cu124"
        
    validations:
      required: true

  - type: textarea
    id: python-packages
    attributes:
      label: Information about Python Packages (`pip list`)
      description: "Please paste the complete output of `pip list`."
      render: python
    validations:
      required: true

  - type: input
    id: trace-id
    attributes:
      label: Trace-ID in the request head
      description: "Please copy and paste the trace-ID of the problematic request."
    validations:
      required: true

  - type: textarea
    attributes:
      label: Description
      description: |
        Please describe the bug you have encountered when using the MCP tools or API.
        The following template is recommended.
        Feel free to modify as you needed.
      value: |
        #### Steps to reproduce

        This happens to Minimax_M1 and xxx.
        The bug can be reproduced with the following steps:
        1. ...
        2. ...

        The following example input & output can be used:
        ```
        system: ...
        user: ...
        ...
        ```

        #### Expected results

        The results are expected to be ...

        #### Attempts to fix

        I have tried several ways to fix this, including:
        1. adjusting the sampling parameters, but ...
        2. prompt engineering, but ...

        #### Anything else helpful for investigation

        I find that this problem also happens to ... 
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Description of the Bug - Screenshots
      description: "Please paste any screenshots of the error or unexpected behavior here. You can drag and drop images directly into this field."
    validations:
      required: false
